json.partial! "v2/staff_super_admin/carrier_policy_type_availabilities/carrier_policy_type_availability_show_full.json.jbuilder", 
  carrier_policy_type_availability: @carrier_policy_type_availability
