version: '3.7'
services:
  db:
    container_name: gc_v2_db_postgres
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    container_name: gc_v2_db_redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data
    entrypoint: redis-server
    restart: always    
    privileged: true
    sysctls:
      net.core.somaxconn: 1024  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    hostname: elasticsearch
    ports:
      - "9200:9200"    
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e 'development'" 
    volumes:
      - .:/getcovered
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
    env_file:
      - .env
  worker:
    build:
      context: .    
      dockerfile: Dockerfile-worker
    command: bundle exec sidekiq -q stripe,2 -q default
    depends_on:
      - db
      - redis
      - elasticsearch
    volumes:
      - .:/getcovered
    env_file:
      - .env
    environment:
      - PRODUCTION_VERSION=Worker Dev