default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  password: postgres
  port: 5455

production_default: &production_default
  adapter: postgresql
  encoding: utf8

local:
  <<: *default
  database: gc_v2_local

development:
  <<: *default
  database: gc_v2_development
  username: postgres

test:
  <<: *default
  database:  gc_v2_test
  username: <%= ENV.fetch("PGUSER", 'postgres') %>
  password: <%= ENV.fetch("PGPASSWORD", 'password') %>

test_container:
  <<: *default
  host: db
  database: gc_v2_test
  username: postgres