# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password:
  
production_default: &production_default
  adapter: postgresql
  encoding: utf8

local:
  <<: *default
  database: gc_v2_local

development:
  <<: *default
  host: db
  database: gc_v2_development
  username: postgres
  
test:
  <<: *default
  host: db
  database: gc_v2_test
  username: postgres
  
awsdev:
  <<: *production_default
  database: <%= Rails.application.credentials.postgres[:awsdev][:database] %>
  username: <%= Rails.application.credentials.postgres[:awsdev][:username] %>
  password: <%= Rails.application.credentials.postgres[:awsdev][:password] %>
  host: <%= Rails.application.credentials.postgres[:awsdev][:host] %>
  port: <%= Rails.application.credentials.postgres[:awsdev][:port] %>
  
production:
  <<: *default
  database: GetCovered_production
  username: GetCovered
  password: <%= ENV['GETCOVERED_DATABASE_PASSWORD'] %>