local:
  host: http://localhost:9200
  log: true
development: &default
  host: http://localhost:9200
  log: true  
test:
  host: http://elasticsearch:9200
awsdev:
  host: <%= Rails.application.credentials.elasticsearch[:awsdev][:url] %>
production:
  host: Rails.application.secrets.elastic_url