local:
  host: http://127.0.0.1:9200
  log: true
development: &default
  host: http://elasticsearch:9200
  log: true  
test:
  host: http://localhost:9200
test_container:
  host: http://elasticsearch:9200
awsdev:
  host: https://search-gc-nonprod-esd-sv27jbj3vohqctw5o5672xg3a4.us-west-2.es.amazonaws.com
  log: true
aws_staging:
  host: https://search-gc-nonprod-esd-sv27jbj3vohqctw5o5672xg3a4.us-west-2.es.amazonaws.com
  log: true
production:
  host: https://search-gc-prod-esd-kv6es7qb5gn5zdoie2nng6nsaa.us-west-2.es.amazonaws.com
