local:
  host: http://127.0.0.1:9200
  log: true
development: &default
  host: http://elasticsearch:9200
  log: true  
test:
  host: http://elasticsearch:9200
awsdev:
  host: https://search-gc-nonprod-esd-sv27jbj3vohqctw5o5672xg3a4.us-west-2.es.amazonaws.com
  log: true
production:
  host: Rails.application.secrets.elastic_url
