:concurrency: 10
staging:
  :concurrency: 20
production:
  :concurrency: 30

:queues:
  - default
  - stripe
  - elasticsearch

:schedule:
  build_coverage_reports_job:
    cron: '0 0 2 * * *'   # Every day at 2:00 AM
    class: Reports::RunCoverageReportsJob
  detailed_renters_insurance_run_cancelled_policies_job:
    cron: '0 0 2 * * *'   # Every day at 2:00 AM
    class: Reports::DetailedRentersInsurance::RunCancelledPoliciesReportsJob
