:concurrency: 10
awsdev:
  :concurrency: 20
aws_staging:
  :concurrency: 20
staging:
  :concurrency: 20
production:
  :concurrency: 20

:queues:
  - default
  - authtrail
  - stripe
  - elasticsearch
  - mailer
  - mailers

:schedule:
  insurables_refresh_insurable_data:
    cron: '0 */2 * * *'   # Every day at 0:00 AM
    class: Insurables::RefreshInsurableDataJob
  # Compliance
  configuration_sweep_job:
    cron: '0 2 * * *'   # Every day at 3:00 AM
    class: Compliance::Policies::MasterCoverageSweepJob
  first_contact_job:
    cron: '0 3 * * *' # Every Day at 3:00 AM
    class: Compliance::Audit::FirstContactJob
  follow_up_contact_job:
    cron: '0 4 * * *' # Every Day at 4:00 AM
    class: Compliance::Audit::FollowUpContactJob
  final_contact_job:
    cron: '0 5 * * *' # Every Day at 5:00 AM
    class: Compliance::Audit::FinalContactJob
  # Reports
  active_policies_reports_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::ActivePoliciesReportsJob
  confie_report:
    cron: '35 * * * *' # Every hour, thirty-five minutes in
    class: Reports::ConfieReportJob
  # Invoices
  bill_due_invoices:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: BillDueInvoicesJob
  bill_past_due_invoices: # Every day at 2:00 AM
    cron: '0 2 * * *'
    class: BillPastDueInvoicesJob
  make_invoices_missed: # Every day at 3:00 AM
    cron: '0 3 * * *'
    class: MakeInvoicesMissedJob
  make_invoices_available:
    cron: '0 1 * * *'   # Every day at 1:00 AM
    class: MakeInvoicesAvailableJob
  handle_unresponsive_charges:
    cron: '0 3 * * *'   # Every day at 3:00 AM
    class: HandleUnresponsiveChargesJob
  # Policies
  cancel_unpaid_policies:
    cron: '0 1 * * *'   # Every day at 1:00 AM
    class: CancelUnpaidPoliciesJob
  bill_master_policies:
    cron: '0 4 1 * *'   # Each first day of month at 6:00 AM
    class: BillMasterPoliciesJob
  # Leads
  leads_status_update_job:
    cron: '0 6 * * *' # Every day at 6:00 AM
    class: LeadsStatusUpdateJob
  # Leases
  lease_start_check_job:
    cron: '0 6 * * *' # Every day at 6:00 AM
    class: LeaseStartCheckJob
  lease_expiration_check_job:
    cron: '0 6 * * *' # Every day at 6:00 AM
    class: LeaseExpirationCheckJob
  # Emails
  add_coverage:
    cron: '0 0 * * *'   # Every day at 0:00 AM
    class: Policies::AddCoverageJob
  remove_coverage:
    cron: '0 0 * * *'   # Every day at 0:00 AM
    class: Policies::RemoveCoverageJob
  warn_expire_cards_job:
    cron: '0 10 1 * *'  # Each first day of month at 10:00 AM
    class: WarnExpireCardsJob
  warn_all_charge_invoice_job:
    cron: '0 10 * * *'  # Every day at 10:00 AM
    class: WarnAllChargeInvoiceJob
  # Access Tokens
  remove_expired_access_tokens_job:
    cron: '0 0 * * *' # Every day at midnight
    class: RemoveExpiredAccessTokensJob
  # Commissions
  handle_line_item_reductions_job:
    cron: '0 2 * * *' # Every day at 2:00 AM
    class: HandleLineItemReductionsJob
  handle_line_item_changes_job:
    cron: '0 3 * * *' # Every day at 3:00 AM
    class: HandleLineItemChangesJob
  create_commissions_for_policy_premium_item_transactions_job:
    cron: '0 5 * * *' # Every day at 5:00 AM
    class: CreateCommissionsForPolicyPremiumItemTransactionsJob
  gmail_mail_sync_job:
    cron: '30 * * * *' # Every hour, thirty minutes in
    class: GmailMailSyncJob
  # Yardi Sync
  yardi_sync_job:
    cron: '0 1 * * *' # Every day at 1:00 AM
    class: YardiSyncJob
  # Generic Actions
  perform_scheduled_actoins_job:
    cron: '45 * * * *' # every hour, 45 minutes in
    class: PerformScheduledActionsJob
