:concurrency: 10
awsdev:
  :concurrency: 20
aws_staging:
  :concurrency: 20
staging:
  :concurrency: 20
production:
  :concurrency: 20

:queues:
  - default
  - authtrail
  - stripe
  - elasticsearch
  - mailer
  - mailers

:schedule:
  configuration_sweep_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Compliance::Policies::MasterCoverageSweepJob
  first_contact_job:
    cron: '0 3 * * *' # Every Day at 3:00 AM
    class: Compliance::Audit::FirstContactJob
  follow_up_contact_job:
    cron: '0 4 * * *' # Every Day at 4:00 AM
    class: Compliance::Audit::FollowUpContactJob
  final_contact_job:
    cron: '0 5 * * *' # Every Day at 5:00 AM
    class: Compliance::Audit::FinalContactJob
  # Reports
  generate_and_send_cancellation_list_job:
    cron: '30 2 * * *'   # Every day at 2:30 AM
    class: CarrierQBE::GenerateAndSendCancellationListJob
  confie_report:
    cron: '35 * * * *' # Every hour, thirty-five minutes in
    class: Reports::ConfieReportJob
  # Invoices
  bill_due_invoices:
    cron: '30 0 * * *'   # Every day at 12:30 AM
    class: BillDueInvoicesJob
  bill_past_due_invoices:
    cron: '30 0 * * *'   # Every day at 12:30 AM
    class: BillPastDueInvoicesJob
  make_invoices_missed:
    cron: '30 1 * * *'   # Every day at 1:30 AM
    class: MakeInvoicesMissedJob
  make_invoices_available:
    cron: '0 0 * * *'   # Every day at 12:01 AM
    class: MakeInvoicesAvailableJob
  handle_unresponsive_charges:
    cron: '30 1 * * *'   # Every day at 1:30 AM
    class: HandleUnresponsiveChargesJob
  # Policies
  cancel_unpaid_policies:
    cron: '0 1 * * *'   # Every day at 1:00 AM
    class: CancelUnpaidPoliciesJob
  bill_master_policies:
    cron: '0 4 1 * *'   # Each first day of month at 6:00 AM
    class: BillMasterPoliciesJob
  expire:
    cron: '0 23 * * *' # Each day at 11:00 PM
    class: Policies::ExpireJob
  # Leads
  leads_status_update_job:
    cron: '0 6 * * *' # Every day at 6:00 AM
    class: LeadsStatusUpdateJob
  leads_premium_total_calculate_job:
    cron: '0 5 * * *' # Every day at 5:00 AM
    class: LeadsPremiumTotalCalculateJob
  # Leases
  lease_start_check_job:
    cron: '0 6 * * *' # Every day at 6:00 AM
    class: LeaseStartCheckJob
  lease_expiration_check_job:
    cron: '0 6 * * *' # Every day at 6:00 AM
    class: LeaseExpirationCheckJob
  # Emails
  add_coverage:
    cron: '0 0 * * *'   # Every day at 0:00 AM
    class: Policies::AddCoverageJob
  remove_coverage:
    cron: '0 0 * * *'   # Every day at 0:00 AM
    class: Policies::RemoveCoverageJob
  warn_expire_cards_job:
    cron: '0 10 1 * *'  # Each first day of month at 10:00 AM
    class: WarnExpireCardsJob
  warn_all_charge_invoice_job:
    cron: '0 10 * * *'  # Every day at 10:00 AM
    class: WarnAllChargeInvoiceJob
  expiring_soon_job:
    cron: '0 6 * * *' # Every day at 6:00 AM
    class: Compliance::Policies::ExpiringSoonJob
  lapsed_job:
    cron: '0 5 * * *' # Every day at 5:00 AM
    class: Compliance::Policies::LapsedJob
  # Access Tokens
  remove_expired_access_tokens_job:
    cron: '0 0 * * *' # Every day at midnight
    class: RemoveExpiredAccessTokensJob
  # Commissions
  handle_line_item_reductions_job:
    cron: '0 2 * * *' # Every day at 2:00 AM
    class: HandleLineItemReductionsJob
  handle_line_item_changes_job:
    cron: '0 3 * * *' # Every day at 3:00 AM
    class: HandleLineItemChangesJob
  create_commissions_for_policy_premium_item_transactions_job:
    cron: '0 5 * * *' # Every day at 5:00 AM
    class: CreateCommissionsForPolicyPremiumItemTransactionsJob
  gmail_mail_sync_job:
    cron: '0 1 * * *'   # Every day at 1:00 AM
    class: GmailMailSyncJob
  # Yardi Sync
  yardi_sync_job:
    cron: '0 1 * * *' # Every day at 1:00 AM
    class: YardiSyncJob
  # Generic Actions
  perform_scheduled_actions_job:
    cron: '45 * * * *' # every hour, 45 minutes in
    class: PerformScheduledActionsJob
  # Update covered status Job
  update_statuses_job:
    cron: '0 6 * * *' # Daily , 06:00 AM
    class: UpdateStatusesJob
