:concurrency: 10
staging:
  :concurrency: 20
production:
  :concurrency: 30

:queues:
  - default
  - stripe
  - elasticsearch

:schedule:
  # Reports
  coverage_reports_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::CoverageReportsJob
  active_reports_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::ActivityReportsJob
  third_party_soon_to_expire_reports_job:
    cron: '0 0 2 * * *'   # Every day at 2:00 AM
    class: Reports::ThirdPartySoonToExpireReportsJob
  detailed_renters_insurance_active_policies_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::DetailedRentersInsurance::ActivePoliciesReportsJob
  detailed_renters_insurance_cancelled_policies_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::DetailedRentersInsurance::CancelledPoliciesReportsJob
  detailed_renters_insurance_expire_soon_policies_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::DetailedRentersInsurance::ExpireSoonPoliciesReportsJob
  detailed_renters_insurance_pending_cancellation_policies_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::DetailedRentersInsurance::PendingCancellationPoliciesReportsJob
  detailed_renters_insurance_uncovered_units_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::DetailedRentersInsurance::UncoveredUnitsReportsJob
  high_level_activity_report_job:
    cron: '0 2 * * 0'   # Every Sunday at 2:00 AM
    class: Reports::DetailedRentersInsurance::HighLevelActivityReports
  soon_to_expire_reports_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::SoonToExpireReportsJob
  active_policies_reports_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::ActivePoliciesReportsJob
  participation_reports_job:
    cron: '0 2 1 * *'   # Every first day of month at 2:00 AM
    class: Reports::ParticipationReportsJob
  property_unit_verification_reports_job:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: Reports::PropertyUnitVerificationReportsJob
  renewal_policies_create_job:
    cron: '0 2 * * 0'
    class: Reports::RenewalPoliciesCreateJob
  high_level_participation_reports_job:
    cron: '0 2 1 * *'   # Each first day of month at 2:00 AM
    class: Reports::HighLevelParticipationReportsJob
  high_trend_analysis_reports_job:
    cron: '0 2 1 * *'   # Each first day of month at 2:00 AM
    class: Reports::HighLevelTrendAnalysisReportsJob
  # Invoices
  bill_due_invoices:
    cron: '0 2 * * *'   # Every day at 2:00 AM
    class: BillDueInvoicesJob
